repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
      - id: gitlint-ci

  - repo: local
    hooks:
      - id: conventional-pre-commit
        name: Conventional commit
        language: script
        entry: hack/check-conventional-commit.sh
        stages: [commit-msg]
