#!/usr/bin/env bash

# Copyright 2026 The Kubernetes resource-state-metrics Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script verifies that manifests generated by controller-gen (in
# manifests/) match the corresponding manifests generated by jsonnet (in
# jsonnet/manifests/).

set -euo pipefail

MANIFESTS_DIR="manifests"
JSONNET_MANIFESTS_DIR="jsonnet/manifests"
YQ="${YQ:-yq}"

errors=0

for file in "${MANIFESTS_DIR}"/*.yaml; do
    base=$(basename "$file")
    jsonnet_file="${JSONNET_MANIFESTS_DIR}/${base}"

    if [[ ! -f "$jsonnet_file" ]]; then
        continue
    fi

    echo "Comparing ${base}..."

    diff_output=$(diff <("$YQ" -o=json '.' "$file" | jq -S .) <("$YQ" -o=json '.' "$jsonnet_file" | jq -S .) 2>&1) || true
    if [[ -n "$diff_output" ]]; then
        echo "ERROR: ${base} does not match."
        echo "$diff_output"
        errors=$((errors + 1))
    fi
done

if [[ $errors -gt 0 ]]; then
    echo ""
    echo "FAILED: ${errors} manifest(s) do not match."
    exit 1
fi

echo "OK: All manifests match."
