# Copyright 2026 The Kubernetes resource-state-metrics Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# TODO delete this
apiVersion: resource-state-metrics.instrumentation.k8s-sigs.io/v1alpha1
kind: ResourceMetricsMonitor
metadata:
  name: prefilled
  namespace: default
spec:
  # NOTE: "unstructured" is the default resolver.
  configuration: |-
    generators:
      - group: "contoso.com"
        version: "v1alpha1"
        kind: "Bar"
        resource: "bars"
        selectors:
          field: "metadata.namespace=default"
        families:
          - name: "platform_info"
            help: "Information about each Bar instance"
            metrics:
              - resolver: "cel"
                labels:
                  - name: "name"
                    value: "o.metadata.name"
                value: "o.metadata.labels.bar"
              - labels:
                  - name: "environmentType"
                    value: "spec.environmentType"
                  - name: "language"
                    value: "spec.language"
                value: "metadata.labels.foo"
          - name: "platform_replicas"
            help: "Number of replicas for each Bar instance"
            metrics:
              - labels:
                  - name: "name"
                    value: "metadata.name"
                  - name: "dynamicNoResolveShouldOutputMapRepr_CompositeUnsupportedUpstreamForUnstructured"
                    value: "metadata.labels"
                value: "spec.replicas"
      - group: "samplecontroller.k8s.io"
        version: "v1alpha1"
        kind: "Foo"
        resource: "foos"
        selectors:
          label: "app.kubernetes.io/part-of=sample-controller"
        families:
          - name: "foos_info"
            help: "Information about each Foo instance"
            metrics:
              - resolver: "cel"
                labels:
                  - name: "dynamicShouldResolveToName"
                    value: "o.metadata.name"
                  - name: "static"
                    value: "43-1"
                  - name: "dynamicNoResolveShouldRemainTheSame1"
                    value: "o.metadata.labels.baz"
                  - name: "dynamicNoResolveShouldRemainTheSame2"
                    value: "metadata.labels.baz"
                value: "42"
          - name: "foo_replicas"
            help: "Number of replicas for each Foo instance"
            metrics:
              - labels:
                  - name: "name"
                    value: "metadata.name"
                value: "spec.replicas"
      - resolver: "cel"
        group: "contoso.com"
        version: "v1alpha1"
        kind: "Bar"
        resource: "bars"
        labels:
          - name: "job"
            value: "o.metadata.annotations.job"
        families:
          - name: "platform_info_conformance"
            help: "Information about each Bar instance (using existing exhaustive CRS feature-set for conformance)"
            labels:
              - name: "id"
                value: "o.metadata.annotations.id"
            metrics:
              - labels:
                  - name: "name"
                    value: "o.metadata.name"
                  - name: "label_" # Maps will use this prefix to generate labels
                    value: "o.metadata.labels"
                  - name: ""
                    value: "o.spec"
                value: "o.metadata.labels.bar"
